/*******************************************************************************
	Generated by: DLL to C version 3.48
	Date: 2024-1-13
	Description: The implementation code for destroy.dll.
	Website: http://www.dll-decompiler.com
	Technical Support: support@dll-decompiler.com
*******************************************************************************/

#include "stdafx.h"
#include "Destroy.h"


HMODULE g_hDestroy;
BOOL (WINAPI *Destroy_DllEntryPoint)(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpReserved);

extern UCHAR Destroy_text[0xDD000];
extern stDestroy_rdata Destroy_rdata;
extern stDestroy_data Destroy_data;
extern stDestroy_rsrc Destroy_rsrc;
extern stDestroy_reloc Destroy_reloc;

__declspec(align(16)) stDestroy Destroy;

void* __stdcall Destroy_RVA(DWORD rvaAddr)
{
	if(rvaAddr==0)
		return g_hDestroy;
	if(rvaAddr >= 0 && rvaAddr < 0x286000)
		return (UCHAR*)&Destroy + rvaAddr;

	return NULL;
}

BOOL Destroy_Init()
{
	HMODULE hDll;
	DWORD oldProtect;
	DWORD nCodeSize;
	void (*fInitData)(HMODULE,void*,void*);

	oldProtect = PAGE_EXECUTE_READWRITE;
	nCodeSize = Destroy_text(Destroy_CodeEnd) - Destroy_text(Destroy_CodeStart);
	VirtualProtect(Destroy_text(Destroy_CodeStart),nCodeSize,PAGE_EXECUTE_READWRITE,&oldProtect);

	memcpy(&Destroy.Text,&Destroy_text,sizeof(Destroy_text));
	memcpy(&Destroy.Rdata,&Destroy_rdata,sizeof(Destroy_rdata));
	memcpy(&Destroy.Data,&Destroy_data,sizeof(Destroy_data));
	memcpy(&Destroy.Rsrc,&Destroy_rsrc,sizeof(Destroy_rsrc));
	memcpy(&Destroy.Reloc,&Destroy_reloc,sizeof(Destroy_reloc));

	hDll = ::LoadLibraryA("KERNEL32.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"KERNEL32.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x20) = ::GetProcAddress(hDll,"GetProcAddress");
	if(!*((UCHAR*)&Destroy_rdata+0x20))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x24) = ::GetProcAddress(hDll,"GetProcessHeap");
	if(!*((UCHAR*)&Destroy_rdata+0x24))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x28) = ::GetProcAddress(hDll,"FreeLibrary");
	if(!*((UCHAR*)&Destroy_rdata+0x28))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x2C) = ::GetProcAddress(hDll,"IsBadReadPtr");
	if(!*((UCHAR*)&Destroy_rdata+0x2C))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x30) = ::GetProcAddress(hDll,"GetModuleHandleA");
	if(!*((UCHAR*)&Destroy_rdata+0x30))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x34) = ::GetProcAddress(hDll,"GetTickCount");
	if(!*((UCHAR*)&Destroy_rdata+0x34))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x38) = ::GetProcAddress(hDll,"GetModuleHandleW");
	if(!*((UCHAR*)&Destroy_rdata+0x38))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x3C) = ::GetProcAddress(hDll,"Sleep");
	if(!*((UCHAR*)&Destroy_rdata+0x3C))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x40) = ::GetProcAddress(hDll,"WritePrivateProfileStringA");
	if(!*((UCHAR*)&Destroy_rdata+0x40))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x44) = ::GetProcAddress(hDll,"CreateDirectoryA");
	if(!*((UCHAR*)&Destroy_rdata+0x44))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x48) = ::GetProcAddress(hDll,"GetPrivateProfileStringA");
	if(!*((UCHAR*)&Destroy_rdata+0x48))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x4C) = ::GetProcAddress(hDll,"InitializeCriticalSection");
	if(!*((UCHAR*)&Destroy_rdata+0x4C))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x50) = ::GetProcAddress(hDll,"MultiByteToWideChar");
	if(!*((UCHAR*)&Destroy_rdata+0x50))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x54) = ::GetProcAddress(hDll,"GetTickCount64");
	if(!*((UCHAR*)&Destroy_rdata+0x54))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x58) = ::GetProcAddress(hDll,"DeleteCriticalSection");
	if(!*((UCHAR*)&Destroy_rdata+0x58))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x5C) = ::GetProcAddress(hDll,"VirtualQuery");
	if(!*((UCHAR*)&Destroy_rdata+0x5C))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x60) = ::GetProcAddress(hDll,"HeapCreate");
	if(!*((UCHAR*)&Destroy_rdata+0x60))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x64) = ::GetProcAddress(hDll,"GetCurrentProcess");
	if(!*((UCHAR*)&Destroy_rdata+0x64))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x68) = ::GetProcAddress(hDll,"Thread32Next");
	if(!*((UCHAR*)&Destroy_rdata+0x68))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x6C) = ::GetProcAddress(hDll,"Thread32First");
	if(!*((UCHAR*)&Destroy_rdata+0x6C))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x70) = ::GetProcAddress(hDll,"GetCurrentThreadId");
	if(!*((UCHAR*)&Destroy_rdata+0x70))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x74) = ::GetProcAddress(hDll,"SuspendThread");
	if(!*((UCHAR*)&Destroy_rdata+0x74))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x78) = ::GetProcAddress(hDll,"ResumeThread");
	if(!*((UCHAR*)&Destroy_rdata+0x78))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x7C) = ::GetProcAddress(hDll,"CreateToolhelp32Snapshot");
	if(!*((UCHAR*)&Destroy_rdata+0x7C))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x80) = ::GetProcAddress(hDll,"HeapReAlloc");
	if(!*((UCHAR*)&Destroy_rdata+0x80))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x84) = ::GetProcAddress(hDll,"CloseHandle");
	if(!*((UCHAR*)&Destroy_rdata+0x84))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x88) = ::GetProcAddress(hDll,"GetThreadContext");
	if(!*((UCHAR*)&Destroy_rdata+0x88))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x8C) = ::GetProcAddress(hDll,"GetCurrentProcessId");
	if(!*((UCHAR*)&Destroy_rdata+0x8C))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x90) = ::GetProcAddress(hDll,"FlushInstructionCache");
	if(!*((UCHAR*)&Destroy_rdata+0x90))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x94) = ::GetProcAddress(hDll,"SetThreadContext");
	if(!*((UCHAR*)&Destroy_rdata+0x94))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x98) = ::GetProcAddress(hDll,"OpenThread");
	if(!*((UCHAR*)&Destroy_rdata+0x98))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x9C) = ::GetProcAddress(hDll,"GetStdHandle");
	if(!*((UCHAR*)&Destroy_rdata+0x9C))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0xA0) = ::GetProcAddress(hDll,"WriteConsoleA");
	if(!*((UCHAR*)&Destroy_rdata+0xA0))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0xA4) = ::GetProcAddress(hDll,"ReadConsoleA");
	if(!*((UCHAR*)&Destroy_rdata+0xA4))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0xA8) = ::GetProcAddress(hDll,"FreeConsole");
	if(!*((UCHAR*)&Destroy_rdata+0xA8))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0xAC) = ::GetProcAddress(hDll,"SetStdHandle");
	if(!*((UCHAR*)&Destroy_rdata+0xAC))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0xB0) = ::GetProcAddress(hDll,"Beep");
	if(!*((UCHAR*)&Destroy_rdata+0xB0))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0xB4) = ::GetProcAddress(hDll,"HeapAlloc");
	if(!*((UCHAR*)&Destroy_rdata+0xB4))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0xB8) = ::GetProcAddress(hDll,"GetModuleFileNameA");
	if(!*((UCHAR*)&Destroy_rdata+0xB8))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0xBC) = ::GetProcAddress(hDll,"GlobalAlloc");
	if(!*((UCHAR*)&Destroy_rdata+0xBC))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0xC0) = ::GetProcAddress(hDll,"GlobalFree");
	if(!*((UCHAR*)&Destroy_rdata+0xC0))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0xC4) = ::GetProcAddress(hDll,"GlobalLock");
	if(!*((UCHAR*)&Destroy_rdata+0xC4))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0xC8) = ::GetProcAddress(hDll,"GlobalUnlock");
	if(!*((UCHAR*)&Destroy_rdata+0xC8))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0xCC) = ::GetProcAddress(hDll,"QueryPerformanceFrequency");
	if(!*((UCHAR*)&Destroy_rdata+0xCC))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0xD0) = ::GetProcAddress(hDll,"QueryPerformanceCounter");
	if(!*((UCHAR*)&Destroy_rdata+0xD0))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0xD4) = ::GetProcAddress(hDll,"FreeLibraryAndExitThread");
	if(!*((UCHAR*)&Destroy_rdata+0xD4))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0xD8) = ::GetProcAddress(hDll,"DisableThreadLibraryCalls");
	if(!*((UCHAR*)&Destroy_rdata+0xD8))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0xDC) = ::GetProcAddress(hDll,"LoadLibraryW");
	if(!*((UCHAR*)&Destroy_rdata+0xDC))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0xE0) = ::GetProcAddress(hDll,"CreateThread");
	if(!*((UCHAR*)&Destroy_rdata+0xE0))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0xE4) = ::GetProcAddress(hDll,"WriteConsoleW");
	if(!*((UCHAR*)&Destroy_rdata+0xE4))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0xE8) = ::GetProcAddress(hDll,"FreeEnvironmentStringsW");
	if(!*((UCHAR*)&Destroy_rdata+0xE8))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0xEC) = ::GetProcAddress(hDll,"GetEnvironmentStringsW");
	if(!*((UCHAR*)&Destroy_rdata+0xEC))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0xF0) = ::GetProcAddress(hDll,"GetCommandLineW");
	if(!*((UCHAR*)&Destroy_rdata+0xF0))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0xF4) = ::GetProcAddress(hDll,"GetCommandLineA");
	if(!*((UCHAR*)&Destroy_rdata+0xF4))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0xF8) = ::GetProcAddress(hDll,"GetOEMCP");
	if(!*((UCHAR*)&Destroy_rdata+0xF8))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0xFC) = ::GetProcAddress(hDll,"GetACP");
	if(!*((UCHAR*)&Destroy_rdata+0xFC))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x100) = ::GetProcAddress(hDll,"IsValidCodePage");
	if(!*((UCHAR*)&Destroy_rdata+0x100))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x104) = ::GetProcAddress(hDll,"HeapSize");
	if(!*((UCHAR*)&Destroy_rdata+0x104))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x108) = ::GetProcAddress(hDll,"GetTimeZoneInformation");
	if(!*((UCHAR*)&Destroy_rdata+0x108))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x10C) = ::GetProcAddress(hDll,"ReadConsoleW");
	if(!*((UCHAR*)&Destroy_rdata+0x10C))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x110) = ::GetProcAddress(hDll,"EnumSystemLocalesW");
	if(!*((UCHAR*)&Destroy_rdata+0x110))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x114) = ::GetProcAddress(hDll,"GetUserDefaultLCID");
	if(!*((UCHAR*)&Destroy_rdata+0x114))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x118) = ::GetProcAddress(hDll,"IsValidLocale");
	if(!*((UCHAR*)&Destroy_rdata+0x118))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x11C) = ::GetProcAddress(hDll,"GetTimeFormatW");
	if(!*((UCHAR*)&Destroy_rdata+0x11C))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x120) = ::GetProcAddress(hDll,"GetDateFormatW");
	if(!*((UCHAR*)&Destroy_rdata+0x120))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x124) = ::GetProcAddress(hDll,"GetConsoleMode");
	if(!*((UCHAR*)&Destroy_rdata+0x124))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x128) = ::GetProcAddress(hDll,"GetConsoleOutputCP");
	if(!*((UCHAR*)&Destroy_rdata+0x128))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x12C) = ::GetProcAddress(hDll,"WriteFile");
	if(!*((UCHAR*)&Destroy_rdata+0x12C))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x130) = ::GetProcAddress(hDll,"FlushFileBuffers");
	if(!*((UCHAR*)&Destroy_rdata+0x130))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x134) = ::GetProcAddress(hDll,"GetFileType");
	if(!*((UCHAR*)&Destroy_rdata+0x134))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x138) = ::GetProcAddress(hDll,"GetFileSizeEx");
	if(!*((UCHAR*)&Destroy_rdata+0x138))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x13C) = ::GetProcAddress(hDll,"ExitProcess");
	if(!*((UCHAR*)&Destroy_rdata+0x13C))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x140) = ::GetProcAddress(hDll,"GetNativeSystemInfo");
	if(!*((UCHAR*)&Destroy_rdata+0x140))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x144) = ::GetProcAddress(hDll,"LoadLibraryA");
	if(!*((UCHAR*)&Destroy_rdata+0x144))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x148) = ::GetProcAddress(hDll,"VirtualAlloc");
	if(!*((UCHAR*)&Destroy_rdata+0x148))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x14C) = ::GetProcAddress(hDll,"VirtualFree");
	if(!*((UCHAR*)&Destroy_rdata+0x14C))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x150) = ::GetProcAddress(hDll,"DeleteFileW");
	if(!*((UCHAR*)&Destroy_rdata+0x150))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x154) = ::GetProcAddress(hDll,"RemoveDirectoryW");
	if(!*((UCHAR*)&Destroy_rdata+0x154))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x158) = ::GetProcAddress(hDll,"SetEnvironmentVariableW");
	if(!*((UCHAR*)&Destroy_rdata+0x158))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x15C) = ::GetProcAddress(hDll,"SetLastError");
	if(!*((UCHAR*)&Destroy_rdata+0x15C))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x160) = ::GetProcAddress(hDll,"HeapFree");
	if(!*((UCHAR*)&Destroy_rdata+0x160))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x164) = ::GetProcAddress(hDll,"WriteProcessMemory");
	if(!*((UCHAR*)&Destroy_rdata+0x164))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x168) = ::GetProcAddress(hDll,"VirtualProtect");
	if(!*((UCHAR*)&Destroy_rdata+0x168))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x16C) = ::GetProcAddress(hDll,"GetModuleHandleExW");
	if(!*((UCHAR*)&Destroy_rdata+0x16C))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x170) = ::GetProcAddress(hDll,"ExitThread");
	if(!*((UCHAR*)&Destroy_rdata+0x170))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x174) = ::GetProcAddress(hDll,"ReadFile");
	if(!*((UCHAR*)&Destroy_rdata+0x174))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x178) = ::GetProcAddress(hDll,"GetLastError");
	if(!*((UCHAR*)&Destroy_rdata+0x178))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x17C) = ::GetProcAddress(hDll,"FormatMessageW");
	if(!*((UCHAR*)&Destroy_rdata+0x17C))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x180) = ::GetProcAddress(hDll,"WideCharToMultiByte");
	if(!*((UCHAR*)&Destroy_rdata+0x180))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x184) = ::GetProcAddress(hDll,"DuplicateHandle");
	if(!*((UCHAR*)&Destroy_rdata+0x184))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x188) = ::GetProcAddress(hDll,"WaitForSingleObjectEx");
	if(!*((UCHAR*)&Destroy_rdata+0x188))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x18C) = ::GetProcAddress(hDll,"SwitchToThread");
	if(!*((UCHAR*)&Destroy_rdata+0x18C))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x190) = ::GetProcAddress(hDll,"GetCurrentThread");
	if(!*((UCHAR*)&Destroy_rdata+0x190))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x194) = ::GetProcAddress(hDll,"CreateDirectoryW");
	if(!*((UCHAR*)&Destroy_rdata+0x194))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x198) = ::GetProcAddress(hDll,"CreateFileW");
	if(!*((UCHAR*)&Destroy_rdata+0x198))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x19C) = ::GetProcAddress(hDll,"FindClose");
	if(!*((UCHAR*)&Destroy_rdata+0x19C))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x1A0) = ::GetProcAddress(hDll,"FindFirstFileExW");
	if(!*((UCHAR*)&Destroy_rdata+0x1A0))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x1A4) = ::GetProcAddress(hDll,"FindNextFileW");
	if(!*((UCHAR*)&Destroy_rdata+0x1A4))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x1A8) = ::GetProcAddress(hDll,"GetFileAttributesExW");
	if(!*((UCHAR*)&Destroy_rdata+0x1A8))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x1AC) = ::GetProcAddress(hDll,"SetEndOfFile");
	if(!*((UCHAR*)&Destroy_rdata+0x1AC))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x1B0) = ::GetProcAddress(hDll,"SetFilePointerEx");
	if(!*((UCHAR*)&Destroy_rdata+0x1B0))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x1B4) = ::GetProcAddress(hDll,"AreFileApisANSI");
	if(!*((UCHAR*)&Destroy_rdata+0x1B4))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x1B8) = ::GetProcAddress(hDll,"EnterCriticalSection");
	if(!*((UCHAR*)&Destroy_rdata+0x1B8))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x1BC) = ::GetProcAddress(hDll,"LeaveCriticalSection");
	if(!*((UCHAR*)&Destroy_rdata+0x1BC))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x1C0) = ::GetProcAddress(hDll,"TryEnterCriticalSection");
	if(!*((UCHAR*)&Destroy_rdata+0x1C0))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x1C4) = ::GetProcAddress(hDll,"InitializeCriticalSectionAndSpinCount");
	if(!*((UCHAR*)&Destroy_rdata+0x1C4))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x1C8) = ::GetProcAddress(hDll,"CreateEventW");
	if(!*((UCHAR*)&Destroy_rdata+0x1C8))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x1CC) = ::GetProcAddress(hDll,"TlsAlloc");
	if(!*((UCHAR*)&Destroy_rdata+0x1CC))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x1D0) = ::GetProcAddress(hDll,"TlsGetValue");
	if(!*((UCHAR*)&Destroy_rdata+0x1D0))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x1D4) = ::GetProcAddress(hDll,"TlsSetValue");
	if(!*((UCHAR*)&Destroy_rdata+0x1D4))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x1D8) = ::GetProcAddress(hDll,"TlsFree");
	if(!*((UCHAR*)&Destroy_rdata+0x1D8))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x1DC) = ::GetProcAddress(hDll,"GetSystemTimeAsFileTime");
	if(!*((UCHAR*)&Destroy_rdata+0x1DC))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x1E0) = ::GetProcAddress(hDll,"EncodePointer");
	if(!*((UCHAR*)&Destroy_rdata+0x1E0))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x1E4) = ::GetProcAddress(hDll,"DecodePointer");
	if(!*((UCHAR*)&Destroy_rdata+0x1E4))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x1E8) = ::GetProcAddress(hDll,"CompareStringW");
	if(!*((UCHAR*)&Destroy_rdata+0x1E8))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x1EC) = ::GetProcAddress(hDll,"LCMapStringW");
	if(!*((UCHAR*)&Destroy_rdata+0x1EC))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x1F0) = ::GetProcAddress(hDll,"GetLocaleInfoW");
	if(!*((UCHAR*)&Destroy_rdata+0x1F0))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x1F4) = ::GetProcAddress(hDll,"GetStringTypeW");
	if(!*((UCHAR*)&Destroy_rdata+0x1F4))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x1F8) = ::GetProcAddress(hDll,"GetCPInfo");
	if(!*((UCHAR*)&Destroy_rdata+0x1F8))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x1FC) = ::GetProcAddress(hDll,"SetEvent");
	if(!*((UCHAR*)&Destroy_rdata+0x1FC))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x200) = ::GetProcAddress(hDll,"ResetEvent");
	if(!*((UCHAR*)&Destroy_rdata+0x200))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x204) = ::GetProcAddress(hDll,"IsDebuggerPresent");
	if(!*((UCHAR*)&Destroy_rdata+0x204))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x208) = ::GetProcAddress(hDll,"UnhandledExceptionFilter");
	if(!*((UCHAR*)&Destroy_rdata+0x208))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x20C) = ::GetProcAddress(hDll,"SetUnhandledExceptionFilter");
	if(!*((UCHAR*)&Destroy_rdata+0x20C))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x210) = ::GetProcAddress(hDll,"GetStartupInfoW");
	if(!*((UCHAR*)&Destroy_rdata+0x210))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x214) = ::GetProcAddress(hDll,"IsProcessorFeaturePresent");
	if(!*((UCHAR*)&Destroy_rdata+0x214))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x218) = ::GetProcAddress(hDll,"InitializeSListHead");
	if(!*((UCHAR*)&Destroy_rdata+0x218))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x21C) = ::GetProcAddress(hDll,"TerminateProcess");
	if(!*((UCHAR*)&Destroy_rdata+0x21C))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x220) = ::GetProcAddress(hDll,"CreateTimerQueue");
	if(!*((UCHAR*)&Destroy_rdata+0x220))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x224) = ::GetProcAddress(hDll,"SignalObjectAndWait");
	if(!*((UCHAR*)&Destroy_rdata+0x224))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x228) = ::GetProcAddress(hDll,"SetThreadPriority");
	if(!*((UCHAR*)&Destroy_rdata+0x228))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x22C) = ::GetProcAddress(hDll,"GetThreadPriority");
	if(!*((UCHAR*)&Destroy_rdata+0x22C))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x230) = ::GetProcAddress(hDll,"GetLogicalProcessorInformation");
	if(!*((UCHAR*)&Destroy_rdata+0x230))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x234) = ::GetProcAddress(hDll,"CreateTimerQueueTimer");
	if(!*((UCHAR*)&Destroy_rdata+0x234))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x238) = ::GetProcAddress(hDll,"ChangeTimerQueueTimer");
	if(!*((UCHAR*)&Destroy_rdata+0x238))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x23C) = ::GetProcAddress(hDll,"DeleteTimerQueueTimer");
	if(!*((UCHAR*)&Destroy_rdata+0x23C))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x240) = ::GetProcAddress(hDll,"GetNumaHighestNodeNumber");
	if(!*((UCHAR*)&Destroy_rdata+0x240))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x244) = ::GetProcAddress(hDll,"GetProcessAffinityMask");
	if(!*((UCHAR*)&Destroy_rdata+0x244))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x248) = ::GetProcAddress(hDll,"SetThreadAffinityMask");
	if(!*((UCHAR*)&Destroy_rdata+0x248))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x24C) = ::GetProcAddress(hDll,"RegisterWaitForSingleObject");
	if(!*((UCHAR*)&Destroy_rdata+0x24C))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x250) = ::GetProcAddress(hDll,"UnregisterWait");
	if(!*((UCHAR*)&Destroy_rdata+0x250))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x254) = ::GetProcAddress(hDll,"GetThreadTimes");
	if(!*((UCHAR*)&Destroy_rdata+0x254))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x258) = ::GetProcAddress(hDll,"GetModuleFileNameW");
	if(!*((UCHAR*)&Destroy_rdata+0x258))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x25C) = ::GetProcAddress(hDll,"LoadLibraryExW");
	if(!*((UCHAR*)&Destroy_rdata+0x25C))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x260) = ::GetProcAddress(hDll,"GetVersionExW");
	if(!*((UCHAR*)&Destroy_rdata+0x260))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x264) = ::GetProcAddress(hDll,"ReleaseSemaphore");
	if(!*((UCHAR*)&Destroy_rdata+0x264))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x268) = ::GetProcAddress(hDll,"InterlockedPopEntrySList");
	if(!*((UCHAR*)&Destroy_rdata+0x268))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x26C) = ::GetProcAddress(hDll,"InterlockedPushEntrySList");
	if(!*((UCHAR*)&Destroy_rdata+0x26C))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x270) = ::GetProcAddress(hDll,"InterlockedFlushSList");
	if(!*((UCHAR*)&Destroy_rdata+0x270))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x274) = ::GetProcAddress(hDll,"QueryDepthSList");
	if(!*((UCHAR*)&Destroy_rdata+0x274))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x278) = ::GetProcAddress(hDll,"UnregisterWaitEx");
	if(!*((UCHAR*)&Destroy_rdata+0x278))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x27C) = ::GetProcAddress(hDll,"RtlUnwind");
	if(!*((UCHAR*)&Destroy_rdata+0x27C))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x280) = ::GetProcAddress(hDll,"RaiseException");
	if(!*((UCHAR*)&Destroy_rdata+0x280))
		return FALSE;

	hDll = ::LoadLibraryA("USER32.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"USER32.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x288) = ::GetProcAddress(hDll,"GetAsyncKeyState");
	if(!*((UCHAR*)&Destroy_rdata+0x288))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x28C) = ::GetProcAddress(hDll,"CallWindowProcA");
	if(!*((UCHAR*)&Destroy_rdata+0x28C))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x290) = ::GetProcAddress(hDll,"SetWindowLongA");
	if(!*((UCHAR*)&Destroy_rdata+0x290))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x294) = ::GetProcAddress(hDll,"FlashWindowEx");
	if(!*((UCHAR*)&Destroy_rdata+0x294))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x298) = ::GetProcAddress(hDll,"SetClipboardData");
	if(!*((UCHAR*)&Destroy_rdata+0x298))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x29C) = ::GetProcAddress(hDll,"GetClipboardData");
	if(!*((UCHAR*)&Destroy_rdata+0x29C))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x2A0) = ::GetProcAddress(hDll,"EmptyClipboard");
	if(!*((UCHAR*)&Destroy_rdata+0x2A0))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x2A4) = ::GetProcAddress(hDll,"CloseClipboard");
	if(!*((UCHAR*)&Destroy_rdata+0x2A4))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x2A8) = ::GetProcAddress(hDll,"OpenClipboard");
	if(!*((UCHAR*)&Destroy_rdata+0x2A8))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x2AC) = ::GetProcAddress(hDll,"GetKeyState");
	if(!*((UCHAR*)&Destroy_rdata+0x2AC))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x2B0) = ::GetProcAddress(hDll,"LoadCursorA");
	if(!*((UCHAR*)&Destroy_rdata+0x2B0))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x2B4) = ::GetProcAddress(hDll,"ScreenToClient");
	if(!*((UCHAR*)&Destroy_rdata+0x2B4))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x2B8) = ::GetProcAddress(hDll,"GetCapture");
	if(!*((UCHAR*)&Destroy_rdata+0x2B8))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x2BC) = ::GetProcAddress(hDll,"ClientToScreen");
	if(!*((UCHAR*)&Destroy_rdata+0x2BC))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x2C0) = ::GetProcAddress(hDll,"IsChild");
	if(!*((UCHAR*)&Destroy_rdata+0x2C0))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x2C4) = ::GetProcAddress(hDll,"GetForegroundWindow");
	if(!*((UCHAR*)&Destroy_rdata+0x2C4))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x2C8) = ::GetProcAddress(hDll,"SetCapture");
	if(!*((UCHAR*)&Destroy_rdata+0x2C8))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x2CC) = ::GetProcAddress(hDll,"SetCursor");
	if(!*((UCHAR*)&Destroy_rdata+0x2CC))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x2D0) = ::GetProcAddress(hDll,"GetClientRect");
	if(!*((UCHAR*)&Destroy_rdata+0x2D0))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x2D4) = ::GetProcAddress(hDll,"ReleaseCapture");
	if(!*((UCHAR*)&Destroy_rdata+0x2D4))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x2D8) = ::GetProcAddress(hDll,"SetCursorPos");
	if(!*((UCHAR*)&Destroy_rdata+0x2D8))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x2DC) = ::GetProcAddress(hDll,"GetCursorPos");
	if(!*((UCHAR*)&Destroy_rdata+0x2DC))
		return FALSE;

	hDll = ::LoadLibraryA("ADVAPI32.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"ADVAPI32.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x0) = ::GetProcAddress(hDll,"RegQueryValueExA");
	if(!*((UCHAR*)&Destroy_rdata+0x0))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x4) = ::GetProcAddress(hDll,"RegCloseKey");
	if(!*((UCHAR*)&Destroy_rdata+0x4))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x8) = ::GetProcAddress(hDll,"RegOpenKeyExA");
	if(!*((UCHAR*)&Destroy_rdata+0x8))
		return FALSE;

	hDll = ::LoadLibraryA("d3dx9_43.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"d3dx9_43.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x300) = ::GetProcAddress(hDll,"D3DXCreateTextureFromFileInMemoryEx");
	if(!*((UCHAR*)&Destroy_rdata+0x300))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x304) = ::GetProcAddress(hDll,"D3DXCreateTextureFromFileInMemory");
	if(!*((UCHAR*)&Destroy_rdata+0x304))
		return FALSE;

	hDll = ::LoadLibraryA("WINMM.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"WINMM.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x2F8) = ::GetProcAddress(hDll,"PlaySoundA");
	if(!*((UCHAR*)&Destroy_rdata+0x2F8))
		return FALSE;

	hDll = ::LoadLibraryA("IMM32.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"IMM32.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x10) = ::GetProcAddress(hDll,"ImmSetCompositionWindow");
	if(!*((UCHAR*)&Destroy_rdata+0x10))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x14) = ::GetProcAddress(hDll,"ImmReleaseContext");
	if(!*((UCHAR*)&Destroy_rdata+0x14))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x18) = ::GetProcAddress(hDll,"ImmGetContext");
	if(!*((UCHAR*)&Destroy_rdata+0x18))
		return FALSE;

	hDll = ::LoadLibraryA("WININET.dll");
	if(!hDll)
	{
#ifdef _DEBUG
		MessageBoxA(NULL,
			"Please copy the dependent DLL \"WININET.dll\" to the working directory.",
			"Load DLL Failed",MB_OK|MB_ICONERROR);
#endif
		ASSERT(0);
		return FALSE;
	}
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x2E4) = ::GetProcAddress(hDll,"InternetCloseHandle");
	if(!*((UCHAR*)&Destroy_rdata+0x2E4))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x2E8) = ::GetProcAddress(hDll,"InternetOpenA");
	if(!*((UCHAR*)&Destroy_rdata+0x2E8))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x2EC) = ::GetProcAddress(hDll,"InternetOpenUrlA");
	if(!*((UCHAR*)&Destroy_rdata+0x2EC))
		return FALSE;
	*(FARPROC*)((UCHAR*)&Destroy.Rdata+0x2F0) = ::GetProcAddress(hDll,"InternetReadFile");
	if(!*((UCHAR*)&Destroy_rdata+0x2F0))
		return FALSE;

	*(FARPROC*)&fInitData = (FARPROC)&Destroy_InitData[0];
	fInitData(g_hDestroy,Destroy_RVA,NULL);

	*(FARPROC*)&Destroy_DllEntryPoint = (FARPROC)Destroy_VA(0x10097F58);
	return TRUE;
}


