/*******************************************************************************
	Generated by: DLL to C version 3.48
	Date: 2024-1-13
	Description: The declaration of functions and variables for destroy.dll.
	Website: http://www.dll-decompiler.com
	Technical Support: support@dll-decompiler.com
*******************************************************************************/

#if !defined(_DESTROY_SUPP_H_00286000_INCLUDED_)
#define _DESTROY_SUPP_H_00286000_INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000


#include <windows.h>

#pragma pack(push)
#pragma pack(1)

#include "Destroy_rdata.h"
#include "Destroy_data.h"
#include "Destroy_rsrc.h"
#include "Destroy_reloc.h"

__declspec(align(16)) struct stDestroy
{
	UCHAR Header[0x1000];
	UCHAR Text[0xDD000];
	stDestroy_rdata Rdata;
	stDestroy_data Data;
	stDestroy_rsrc Rsrc;
	stDestroy_reloc Reloc;
};

#pragma pack(pop)

__declspec(align(16)) extern stDestroy Destroy;

/* Export Symbols in the .text section */
enum{
	Destroy_CodeEnd = 0,
};

/* .text section, RVA range: 0x1000 - 0xDE000 */
UCHAR* __stdcall Destroy_text(INT iSymbol);

/* Data for initialization. */
extern UCHAR Destroy_InitData[0x0];

extern HMODULE g_hDestroy;

/*
	Description: Access any address in the DLL.
	Parameters:
		rvaAddr: The RVA address you want to access.
*/
void* __stdcall Destroy_RVA(DWORD rvaAddr);

#define Destroy_VA(vaAddr) Destroy_RVA((vaAddr) - 0x10000000)


#endif // !defined(_DESTROY_SUPP_H_00286000_INCLUDED_)